service: node-html-pdf

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  pdfConverter:
    handler: handler.handler
    events:
      - http:
          path: /pdf
          method: get
          cors: true

plugins:
  - serverless-offline